site_name: Gurpeiros
site_url: https://gurpeiros.com.br/

theme:
  name: material
  language: pt-BR
  logo: assets/imagens/PoweredByGURPS.png
  favicon: assets/imagens/dice.png
  custom_dir: overrides
  palette:
    scheme: slate # dark mode
    primary: black
    accent: amber

use_directory_urls: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
  - stylesheets/grimorio.css

extra_javascript:
  - javascripts/grimorio.js


nav:
  - Início: index.md

  - Regras da Casa:
      - Resumo: regras/index.md
      - Assinaturas: 
         - Visão Geral: regras/assinatura/index.md
         - Como construir: regras/assinatura/assinatura_construcao.md
         - Tipos de assinatura: regras/assinatura/assinatura_tipo.md            
         - Destino e complicações: regras/assinatura/assinatura_destino.md                     
         - Categorias de complicações: regras/assinatura/assinatura_complicacao.md                              
      - Magias:
          - Sobre Magia: regras/magia/index.md
          - Magia de Domínio: 
            - Introdução: regras/magia/magia_dominios.md
            - Requisitos do Mago de Domínio: regras/magia/dominio_requisitos.md
            - Lista de Domínios: regras/magia/dominio_lista.md
            - Elementos da magia e como classificar: regras/magia/dominio_elementos.md
            - Operação da magia: regras/magia/dominio_operacao.md
            - Aprendendo um novo domínio: regras/magia/dominio_aprendizagem.md
            - Critérios de Aplicação das Tabelas de Penalidades: regras/magia/dominio_criterios.md
            - Grimório de Magias: regras/magia/grimorio.md
          - Magia do Limiar:
            - Regras gerais: regras/magia/magia_limiar.md
            - Efeitos adicionais: regras/magia/efeitos_adicionais.md
            - Limiar e mana: regras/magia/limiar_mana.md
            - Limiar e magia cerimonial: regras/magia/magia_cerimonial.md
            - Limiar e magias de energia: regras/magia/magias_energia.md
            - Limiar e os Itens de Poder: regras/magia/limiar_itens_de_poder.md
      - Tabelas:
         - Calamidades (Magia do Limiar): regras/tabelas/calamidades.md
         - Golpes Épicos: regras/tabelas/golpes_epicos.md
         - Efeitos Épicos em magias: regras/tabelas/magia_epica.md
         - Penalidades (Magia de Domínio): regras/tabelas/penalidades_dominio.md
  - Cenários:
      - Sobre Cenários: cenarios/index.md
      - Zandia:
          - Sobre Zandia: cenarios/zandia/index.md
          - Origem: cenarios/zandia/origem.md
          - Cataclismo: cenarios/zandia/cataclismo.md
          - História: cenarios/zandia/historia.md
          - Mundo:
            - Introdução: cenarios/zandia/mundo/index.md
            - Astronomia: cenarios/zandia/mundo/astronomia.md
            - Calendario: cenarios/zandia/mundo/calendario.md
            - Mar morto: cenarios/zandia/mundo/mar_morto.md
            - Metafísica das Brumas: cenarios/zandia/mundo/metafisica_brumas.md
            - Arquitetos: cenarios/zandia/mundo/arquitetos.md
            - Cidades-Estado: cenarios/zandia/mundo/cidades_estado.md
            - Heliópolis:
              - A Cidade: cenarios/zandia/mundo/heliopolis/index.md            
              - Distritos: cenarios/zandia/mundo/heliopolis/heliopolis_distritos.md            
              - Facções: cenarios/zandia/mundo/heliopolis/heliopolis_faccoes.md            
              - Governo:  cenarios/zandia/mundo/heliopolis/heliopolis_governo.md            
          - Magia:
            - Introdução: cenarios/zandia/magia/index.md
            - Natureza da Magia e Sociedade: cenarios/zandia/magia/magia_natureza.md
          - Personagens:
            - Lista de Personagens: cenarios/zandia/personagens/index.md
          - Raças:
            - As Raças de Zandia: cenarios/zandia/racas/index.md
            - Humanos: cenarios/zandia/racas/humanos.md
            - Anões: cenarios/zandia/racas/dwarfs.md
            - Armadilhos: cenarios/zandia/racas/armadilhos.md
            - Clopas: cenarios/zandia/racas/clopas.md
            - Drows: cenarios/zandia/racas/drows.md
            - Elfos Cinzentos: cenarios/zandia/racas/elfos_cinzentos.md
            - Homens-Chacal: cenarios/zandia/racas/werejackal.md
            - Krin: cenarios/zandia/racas/krin.md
            - Nephalin: cenarios/zandia/racas/nephalin.md
            - Ratinos: cenarios/zandia/racas/ratinos.md
            - Syridianos: cenarios/zandia/racas/syridianos.md
            - Tressi: cenarios/zandia/racas/tressi.md
          - Religião:
            - Visão Geral: cenarios/zandia/religiao/index.md
            - Igreja dos Novos Deuses: cenarios/zandia/religiao/novaigreja.md
            - Patronos: cenarios/zandia/religiao/patronos.md
          - Facções e Organizações: 
            - Facções em Zandia: cenarios/zandia/faccoes/index.md
            - Filhos da Anarquia: cenarios/zandia/faccoes/filhos_anarquia.md
            - Inquisição: cenarios/zandia/faccoes/inquisicao.md
            - Sindicato: cenarios/zandia/faccoes/sindicato.md
            - Nascidos das Brumas: 
              - Sobre os nascidos: cenarios/zandia/faccoes/nascidos_brumas/index.md
              - Origem: cenarios/zandia/faccoes/nascidos_brumas/nascidos_origem.md
              - Sociedade: cenarios/zandia/faccoes/nascidos_brumas/nascidos_sociedade.md
              - A Guerra: cenarios/zandia/faccoes/nascidos_brumas/nascidos_guerra.md
              - Segredos: cenarios/zandia/faccoes/nascidos_brumas/nascidos_segredos.md
          - Ideias e conceitos: 
            - Resumo: cenarios/zandia/ideias/index.md
            - Organizações mágicas: cenarios/zandia/ideias/organizacoes_magicas.md
  - Material de Apoio:
      - Resumo: material/index.md
      - Gerador de Magias (Documentação):
        - Gerador - Regras de negocio: material/gerador-magias/regra-negocio.md
        - Gerador - Esquema JSON: material/gerador-magias/esquema-json.md
      - Artigos do Blog: material/artigos.md
        


