site_name: Gurpeiros
site_url: https://gurpeiros.com.br/

theme:
  name: material
  language: pt-BR

use_directory_urls: true

nav:
  - Início: index.md
  - Campanhas:
      - Visão Geral: campanhas/index.md
  - Regras da Casa:
      - Visão Geral: regras/index.md
  - Artigos:
      - Visão Geral: artigos/index.md